# 07b — Repetir o ajuste fino com taxa de aprendizado menor

Execute no **Colab com GPU T4**, em uma sessão nova. Reutilize o mesmo ZIP
HomeObjects + SUN RGB-D e o mesmo `best.pt` **antigo** já enviados ao Drive.

O experimento anterior parou na época 11 e seu melhor resultado foi na época 1.
Este experimento testa uma hipótese: reduzir **somente a taxa inicial de
aprendizado de 0.0003 para 0.00003**, dez vezes menor. O objetivo é fazer
mudanças menores nos pesos. Melhoria ainda precisa ser medida.

Os parâmetros de treinamento restantes seguem o 07: até 30 épocas, patience
10, batch 16, imagens 640, seed 42, AdamW e os mesmos aumentos de dados.
A agenda relativa de aprendizado é igual, com os valores reduzidos pela nova
taxa inicial. A avaliação registra também o baseline na validação mista e
compara o resultado com o primeiro ajuste fino, quando seus relatórios estiverem
na pasta anterior do Drive. Essas avaliações adicionais não mudam o treino.

A seleção usa validação. As 403 imagens TEST continuam fora da seleção e
do treinamento. A arquitetura, os 12 IDs e a política V2 seguem os existentes.

## 1. Instalar a versão definida e ativar a GPU

Usamos a versão do Ultralytics das comparações locais anteriores. Se o Colab pedir
reinício depois de instalar, reinicie e execute novamente a partir desta etapa.

In [1]:
%pip install -q ultralytics==8.4.150 pyyaml pandas pillow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 13.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.8/96.8 kB 1.9 MB/s eta 0:00:00

In [2]:
import sys
import json
import hashlib
import platform
import shutil
import zipfile
from datetime import datetime, timezone
from pathlib import Path
import pandas as pd
import yaml
import torch
import ultralytics
from ultralytics import YOLO
from IPython.display import display

if not torch.cuda.is_available():
    raise RuntimeError("No Colab, selecione Ambiente de execução → Alterar tipo → GPU T4 e reconecte.")
if ultralytics.__version__ != "8.4.150":
    raise RuntimeError("Reinicie o ambiente para carregar ultralytics==8.4.150.")
print("Python:", platform.python_version())
print("PyTorch:", torch.__version__)
print("Ultralytics:", ultralytics.__version__)
print("GPU:", torch.cuda.get_device_name(0))

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.
Python: 3.13.15
PyTorch: 2.11.0+cu130
Ultralytics: 8.4.150
GPU: Tesla T4

## 2. Montar o Drive e conferir as entradas

No Meu Drive, dentro de `TCC_Visao_Computacional`, use:

| Arquivo | Caminho |
|---|---|
| ZIP gerado no 06 | `datasets/homeobjects_sunrgbd_validado.zip` |
| Modelo antigo | `modelos/yolov8n_baseline/best.pt` |

Os resultados vão para uma pasta nova com data/hora. Não substituem o baseline.

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [4]:
DRIVE_TCC = Path("/content/drive/MyDrive/TCC_Visao_Computacional")
ZIP_DATASET = DRIVE_TCC / "datasets/homeobjects_sunrgbd_validado.zip"
MODELO_ANTIGO_DRIVE = DRIVE_TCC / "modelos/yolov8n_baseline/best.pt"
SHA_MODELO_ANTIGO = "4170653e0c0a604f85b6747e42b3fd2ff5ddb765ee4762915dfc9f3d33d322d9"
NOME_EXPERIMENTO = "yolov8n_baseline_sunrgbd_lr_menor_" + datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S_%f")
PASTA_TRABALHO = Path("/content/tcc_sunrgbd") / NOME_EXPERIMENTO
PASTA_RESULTADOS = DRIVE_TCC / "resultados" / NOME_EXPERIMENTO
PASTA_RUN = PASTA_RESULTADOS / "treinamento"

# Mesmo experimento de dados; a mudança de treino é somente LR0.
EPOCHS = 30
PATIENCE = 10
BATCH = 16
IMGSZ = 640
SEED = 42
WORKERS = 2
LR0 = 0.00003

def sha256_arquivo(caminho):
    h = hashlib.sha256()
    with Path(caminho).open("rb") as f:
        for bloco in iter(lambda: f.read(1024 * 1024), b""):
            h.update(bloco)
    return h.hexdigest()

for p in [ZIP_DATASET, MODELO_ANTIGO_DRIVE]:
    if not p.is_file():
        raise FileNotFoundError(f"Arquivo ausente no Drive: {p}")
if sha256_arquivo(MODELO_ANTIGO_DRIVE) != SHA_MODELO_ANTIGO:
    raise RuntimeError("O arquivo do Drive não corresponde ao modelo antigo avaliado. Copie o best.pt de models/yolov8n_baseline.")
PASTA_RESULTADOS.mkdir(parents=True, exist_ok=False)
PASTA_TRABALHO.mkdir(parents=True, exist_ok=False)
MODELO_INICIAL = PASTA_TRABALHO / "baseline_inicial.pt"
shutil.copy2(MODELO_ANTIGO_DRIVE, MODELO_INICIAL)
print("Modelo inicial confirmado:", MODELO_INICIAL)
print("Resultados:", PASTA_RESULTADOS)

CONTROLE_07 = json.loads('{"experimento": "yolov8n_baseline_sunrgbd_20261013_120842_048419", "modelo_base_sha256": "4170653e0c0a604f85b6747e42b3fd2ff5ddb765ee4762915dfc9f3d33d322d9", "zip_sha256": "ada7fbee37b83f673b1b76bc57643d1fe4648941e0e8a7b895282216aed47676", "test_sha256": "f48be0a2b3a93e59259b1ae0d3655028951bf270ef7f4e7916a9424530951a89", "politica_sha256": "1aa6b13cb68d8f30a2f388c3577a61a12dcac4c604581877091d3fbdc6042845", "epochs": 30, "patience": 10, "batch": 16, "imgsz": 640, "seed": 42, "workers": 2, "optimizer": "AdamW", "lr0": 0.0003, "resume": false, "mosaic": 0.15, "close_mosaic": 5, "python": "3.13.15", "torch": "2.11.0+cu130", "ultralytics": "8.4.150", "gpu": "Tesla T4"}')
PASTA_ANTERIOR = DRIVE_TCC / "resultados" / CONTROLE_07["experimento"]
if sha256_arquivo(ZIP_DATASET) != CONTROLE_07["zip_sha256"]:
    raise RuntimeError("O ZIP é diferente do usado no 07. Para comparar a taxa, use o mesmo pacote.")
if LR0 != 0.00003:
    raise RuntimeError("Este experimento foi definido com LR0=0.00003.")
print("Experimento anterior:", PASTA_ANTERIOR)
print("Taxa de aprendizado:", CONTROLE_07["lr0"], "→", LR0)

Modelo inicial confirmado: /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/baseline_inicial.pt
Resultados: /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209
Experimento anterior: /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_20261013_120842_048419
Taxa de aprendizado: 0.0003 → 3e-05

## 3. Extrair e conferir o pacote completo

Cada arquivo do manifesto é conferido por SHA-256. Também verificamos os 12 IDs,
as contagens e a ausência de imagens/labels adicionais fora do manifesto.
O YAML do Colab é uma cópia com a raiz local corrigida.

In [5]:
destino = PASTA_TRABALHO.resolve()
with zipfile.ZipFile(ZIP_DATASET) as pacote:
    nomes_zip = pacote.namelist()
    if len(nomes_zip) != len(set(nomes_zip)):
        raise ValueError("ZIP contém nomes repetidos.")
    for membro in pacote.infolist():
        final = (destino / membro.filename).resolve()
        if final != destino and destino not in final.parents:
            raise ValueError("ZIP contém caminho fora da pasta de trabalho.")
    pacote.extractall(destino)

manifesto = json.loads((PASTA_TRABALHO / "verificacao_preparacao.json").read_text(encoding="utf-8"))
for item in manifesto["arquivos"]:
    arquivo = (PASTA_TRABALHO / item["arquivo"]).resolve()
    if destino not in arquivo.parents or not arquivo.is_file() or sha256_arquivo(arquivo) != item["sha256"]:
        raise RuntimeError(f"Arquivo ausente ou alterado: {item['arquivo']}")
if manifesto["test"]["imagens"] != 403:
    raise RuntimeError("O pacote não preserva o TEST de 403 imagens.")
RAIZ_DATASET = PASTA_TRABALHO / manifesto["dataset_dir"]
dados_yaml = yaml.safe_load((RAIZ_DATASET / "data.yaml").read_text(encoding="utf-8-sig"))
NOMES = {int(k): str(v) for k, v in dados_yaml["names"].items()}
ESPERADAS = dict(enumerate(["bed", "sofa", "chair", "table", "lamp", "tv", "laptop", "wardrobe", "window", "door", "potted plant", "photo frame"]))
if NOMES != ESPERADAS or NOMES != {int(k): v for k, v in manifesto["classes"].items()}:
    raise RuntimeError("Classes/IDs incompatíveis com o baseline.")
verificacao = []
for split in ["train", "val", "test"]:
    for tipo in ["images", "labels"]:
        prefixo = f"{manifesto['dataset_dir']}/{tipo}/{split}/"
        esperados = {i["arquivo"] for i in manifesto["arquivos"] if i["arquivo"].startswith(prefixo)}
        reais = {p.relative_to(PASTA_TRABALHO).as_posix() for p in (RAIZ_DATASET / tipo / split).rglob("*") if p.is_file()}
        if reais != esperados or len(reais) != manifesto["imagens_por_split"][split]:
            raise RuntimeError(f"Arquivos adicionais/ausentes ou contagem diferente: {tipo}/{split}.")
    verificacao.append({"split": split, "imagens": manifesto["imagens_por_split"][split]})
dados_yaml["path"] = RAIZ_DATASET.as_posix()
YAML_MISTO = RAIZ_DATASET / "data_colab.yaml"
YAML_MISTO.write_text(yaml.safe_dump(dados_yaml, sort_keys=False, allow_unicode=True), encoding="utf-8")
sys.path.insert(0, str(PASTA_TRABALHO / "codigo"))
from src.validacao_alertas import carregar_home_val, avaliar_alertas
import src.politica_alertas as politica
REGISTROS_HOME_VAL = carregar_home_val(RAIZ_DATASET, NOMES)
lista_home_val = PASTA_TRABALHO / "home_val.txt"
lista_home_val.write_text("\n".join(str(r["imagem"]) for r in REGISTROS_HOME_VAL) + "\n", encoding="utf-8")
# Uma avaliação de detecção somente na validação Home, separada da validação mista.
YAML_HOME_VAL = PASTA_TRABALHO / "data_home_val.yaml"
home_yaml = {**dados_yaml, "val": str(lista_home_val)}
YAML_HOME_VAL.write_text(yaml.safe_dump(home_yaml, allow_unicode=True, sort_keys=False), encoding="utf-8")
display(pd.DataFrame(verificacao))
print("Validação Home:", len(REGISTROS_HOME_VAL), "imagens")
shutil.copy2(PASTA_TRABALHO / "verificacao_preparacao.json", PASTA_RESULTADOS / "verificacao_preparacao.json")
shutil.copy2(PASTA_TRABALHO / "resumo_preparacao_sunrgbd.json", PASTA_RESULTADOS / "resumo_preparacao_sunrgbd.json")

   split  imagens
0  train     3970
1    val      993
2   test      403

Validação Home: 456 imagens

PosixPath('/content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/resumo_preparacao_sunrgbd.json')

## 4. Registrar configuração e avaliar o antigo na validação Home

O controle e o candidato usam o mesmo conjunto, GPU e parâmetros. As métricas
dos alertas usam confiança 0,25, NMS IoU 0,70, correspondência de mesma classe
com IoU ≥ 0,50 e alertas de prioridade média/alta. As métricas mAP usam 0,001.


Também avaliamos o antigo na **validação mista de 993 imagens**, separadamente
das 456 imagens HomeObjects. Isso fornece o ponto de partida da curva de
treinamento. Não compare diretamente métricas obtidas em conjuntos diferentes.

In [6]:
CONFIGURACAO = {
    "experimento": NOME_EXPERIMENTO, "modelo_base_sha256": SHA_MODELO_ANTIGO,
    "zip_sha256": sha256_arquivo(ZIP_DATASET), "epochs": EPOCHS,
    "patience": PATIENCE, "batch": BATCH, "imgsz": IMGSZ, "seed": SEED,
    "workers": WORKERS, "optimizer": "AdamW", "lr0": LR0,
    "resume": False, "mosaic": 0.15, "close_mosaic": 5,
    "python": platform.python_version(), "ultralytics": ultralytics.__version__,
    "torch": torch.__version__, "gpu": torch.cuda.get_device_name(0),
    "test_sha256": manifesto["test"]["sha256"],
    "politica_sha256": sha256_arquivo(politica.__file__),
    "home_val_imagens": len(REGISTROS_HOME_VAL),
    "criterio_checkpoint": "best.pt por fitness de validação mista do Ultralytics",
    "criterio_triagem": "ganho de precisão de alertas com Recall preservado, na validação Home",
}
CONFIGURACAO["experimento_controle"] = CONTROLE_07["experimento"]
CONFIGURACAO["alteracao_planejada"] = {"lr0": {"antes": 0.0003, "agora": LR0}}
for chave in ["modelo_base_sha256", "zip_sha256", "test_sha256", "politica_sha256",
              "epochs", "patience", "batch", "imgsz", "seed", "workers", "optimizer",
              "resume", "mosaic", "close_mosaic"]:
    if CONFIGURACAO[chave] != CONTROLE_07[chave]:
        raise RuntimeError(f"Outro parâmetro de comparação mudou: {chave}")
diferencas_ambiente = {k: {"antes": CONTROLE_07[k], "agora": CONFIGURACAO[k]}
                      for k in ["python", "torch", "ultralytics", "gpu"]
                      if CONTROLE_07[k] != CONFIGURACAO[k]}
CONFIGURACAO["diferencas_ambiente"] = diferencas_ambiente
if diferencas_ambiente:
    print("Ambiente mudou; considere isso na comparação:", diferencas_ambiente)
(PASTA_RESULTADOS / "configuracao_experimento.json").write_text(
    json.dumps(CONFIGURACAO, ensure_ascii=False, indent=2), encoding="utf-8")

def avaliar_detector_val(modelo, nome, caminho_yaml=YAML_HOME_VAL):
    r = modelo.val(data=str(caminho_yaml), split="val", imgsz=IMGSZ,
                   batch=BATCH, device=0, conf=0.001, iou=0.70, max_det=300,
                   plots=True, project=str(PASTA_RESULTADOS), name=nome, exist_ok=False)
    return {"precision_detector": float(r.box.mp), "recall_detector": float(r.box.mr),
            "map50": float(r.box.map50), "map50_95": float(r.box.map)}

antigo = YOLO(str(MODELO_INICIAL))
if {int(k): str(v) for k, v in antigo.names.items()} != NOMES:
    raise RuntimeError("Modelo antigo tem IDs diferentes dos labels.")
metricas_antigo = {**avaliar_detector_val(antigo, "baseline_home_val"),
                   **avaliar_alertas(antigo, REGISTROS_HOME_VAL, NOMES)}
(PASTA_RESULTADOS / "metricas_baseline_val.json").write_text(json.dumps(metricas_antigo, indent=2, ensure_ascii=False), encoding="utf-8")
print(json.dumps(metricas_antigo, ensure_ascii=False, indent=2))
metricas_baseline_misto = avaliar_detector_val(antigo, "baseline_misto_val", YAML_MISTO)
(PASTA_RESULTADOS / "metricas_baseline_misto_val.json").write_text(
    json.dumps(metricas_baseline_misto, ensure_ascii=False, indent=2), encoding="utf-8")
print("Ponto de partida na validação mista:", metricas_baseline_misto)
del antigo
torch.cuda.empty_cache()

Ultralytics 8.4.150 🚀 Python-3.13.15 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,007,988 parameters, 0 gradients, 8.1 GFLOPs
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 20.9MB/s 0.0s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1724.8±391.5 MB/s, size: 141.4 KB)
val: Scanning /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train... 456 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 456/456 2.2Kit/s 0.2s
val: New cache created: /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 3.1it/s 9.3s
                   all        456       3682      0.883      0.765      0.859      0.664
                   bed         29         29      0.907      0.793      0.879      0.719
                  sofa        294        420      0.912      0.921      0.952      0.792
                 chair        200        428      0.929      0.791      0.906        0.7
                 table        331        513       0.94      0.838      0.929      0.736
                  lamp        216        370      0.884      0.681      0.796      0.544
                    tv         63         67      0.899      0.776      0.917      0.739
                laptop         17         23      0.774      0.522      0.622      0.484
              wardrobe         80         94      0.867      0.702      0.812      0.636
                window        144        323      0.834      0.856       0.91      0.687
                  door         74         94       0.82      0.702       0.79      0.607
          potted plant        316        823      0.895      0.718      0.855      0.558
           photo frame        212        498      0.934       0.88      0.941      0.767
Speed: 1.5ms preprocess, 4.7ms inference, 0.0ms loss, 2.5ms postprocess per image
Results saved to /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/baseline_home_val
Validação dos alertas: 100/456
Validação dos alertas: 200/456
Validação dos alertas: 300/456
Validação dos alertas: 400/456
{
  "precision_detector": 0.882926992323707,
  "recall_detector": 0.7650522432686092,
  "map50": 0.8592072829168672,
  "map50_95": 0.664002379925522,
  "imagens": 456,
  "tp": 1380,
  "fn": 155,
  "fp": 381,
  "alta_sem_alerta": 24,
  "precision_alertas": 0.7836456558773425,
  "recall_alertas": 0.8990228013029316,
  "f1_alertas": 0.837378640776699,
  "referencia": "V2 fixa nas anotações; não valida risco físico independentemente",
  "conf": 0.25,
  "iou_nms": 0.7,
  "iou_correspondencia": 0.5
}
Ultralytics 8.4.150 🚀 Python-3.13.15 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,007,988 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2102.0±1157.5 MB/s, size: 62.2 KB)
val: Scanning /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train... 993 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 993/993 2.2Kit/s 0.5s
val: New cache created: /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 63/63 4.4it/s 14.3s
                   all        993       6936      0.759        0.6      0.672      0.493
                   bed        137        210      0.888      0.333      0.568      0.351
                  sofa        367        524      0.744      0.845      0.847      0.696
                 chair        525       2595      0.866      0.296      0.461      0.272
                 table        610       1053      0.803      0.558      0.658      0.477
                  lamp        286        480      0.808       0.56      0.637      0.416
                    tv         85         91      0.667       0.67      0.731      0.596
                laptop         24         30       0.67      0.433      0.507      0.357
              wardrobe         81         95      0.634      0.695      0.709      0.562
                window        146        325      0.698      0.846      0.846       0.64
                  door        182        212      0.802      0.363      0.467      0.344
          potted plant        316        823      0.816       0.72      0.799      0.525
           photo frame        212        498      0.708      0.881      0.828      0.678
Speed: 1.2ms preprocess, 3.5ms inference, 0.0ms loss, 2.1ms postprocess per image
Results saved to /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/baseline_misto_val
Ponto de partida na validação mista: {'precision_detector': 0.7586986681995942, 'recall_detector': 0.6002758869230559, 'map50': 0.6715865412200186, 'map50_95': 0.49277406968511506}

## 5. Ajuste fino com LR0=0.00003

Inicializamos novamente os pesos do modelo antigo. A taxa inicial é dez vezes
menor. As 30 épocas e patience 10 seguem iguais ao primeiro experimento.
A parada antecipada continua sendo uma possibilidade; o número de épocas
concluídas não determina sozinho a qualidade do resultado.

Os pesos e logs vão para uma **nova pasta** do Drive. O arquivo `best.pt` segue
o critério padrão do Ultralytics na validação mista; os alertas são comparados
depois na mesma validação HomeObjects. Os dados do TEST não escolhem o candidato.

In [7]:
modelo = YOLO(str(MODELO_INICIAL))
resultado_treino = modelo.train(
    data=str(YAML_MISTO), epochs=EPOCHS, patience=PATIENCE,
    imgsz=IMGSZ, batch=BATCH, device=0, workers=WORKERS,
    seed=SEED, deterministic=True, optimizer="AdamW", lr0=LR0,
    lrf=0.10, cos_lr=True, warmup_epochs=2.0, warmup_bias_lr=0.0,
    weight_decay=0.0005, mosaic=0.15, close_mosaic=5,
    mixup=0.0, scale=0.20, translate=0.10, fliplr=0.50,
    resume=False, pretrained=True, save=True, save_period=5,
    plots=True, cache=False, project=str(PASTA_RESULTADOS),
    name="treinamento", exist_ok=False,
)
PASTA_RUN = Path(modelo.trainer.save_dir)
BEST = PASTA_RUN / "weights/best.pt"
if not BEST.is_file():
    raise FileNotFoundError(f"best.pt não produzido: {BEST}")
shutil.copy2(BEST, PASTA_RESULTADOS / "best.pt")
print("Novo candidato preservado:", PASTA_RESULTADOS / "best.pt")
del modelo
torch.cuda.empty_cache()

New https://pypi.org/project/ultralytics/8.4.176 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.150 🚀 Python-3.13.15 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=5, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/data_colab.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=3e-05, lrf=0.1, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/baseline_inicial.pt, momentum=0.937, mosaic=0.15, multi_scale=0.0, name=treinamento, nbs=64, nms=None, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/treinamento, save_frames=False, save_json=False, save_period=5, save_txt=False, scale=0.2, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.0, warmup_epochs=2.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    753652  ultralytics.nn.modules.head.Detect           [12, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,013,188 parameters, 3,013,172 gradients, 8.2 GFLOPs

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 93.5MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1941.2±1315.0 MB/s, size: 108.1 KB)
train: Scanning /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/train/raw_train... 3970 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3970/3970 2.1Kit/s 1.9s
train: New cache created: /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/train/raw_train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1274.0±1288.9 MB/s, size: 126.3 KB)
val: Scanning /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train.cache... 993 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 993/993 119.0Mit/s 0.0s
optimizer: AdamW(lr=3e-05, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/treinamento/labels.jpg...
Using 3970 train, 993 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/treinamento
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30      2.14G      1.157       1.35       1.28         20        640: 100% ━━━━━━━━━━━━ 249/249 3.5it/s 1:10
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.6it/s 12.1s
                   all        993       6936      0.738       0.63      0.686        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30      2.87G      1.118      1.202      1.248         11        640: 100% ━━━━━━━━━━━━ 249/249 3.8it/s 1:06
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.7it/s 11.7s
                   all        993       6936      0.743      0.642      0.712       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30      2.87G      1.096      1.164      1.228          4        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.0it/s 10.8s
                   all        993       6936      0.769      0.638      0.727      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30      2.87G      1.079      1.125      1.214         30        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.2it/s 10.0s
                   all        993       6936       0.76      0.651      0.732      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30      2.87G      1.063      1.099      1.202          6        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.3s
                   all        993       6936      0.756      0.659      0.735      0.538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30      2.87G      1.053      1.079      1.193         10        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.1it/s 10.4s
                   all        993       6936      0.779      0.647      0.737      0.539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30      2.87G      1.048      1.066      1.192         14        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.8it/s 11.3s
                   all        993       6936      0.762      0.668      0.736       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30      2.87G      1.034      1.053      1.182         24        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.9it/s 11.1s
                   all        993       6936      0.749      0.676       0.74      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30      2.87G      1.032      1.034      1.182         14        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:08
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.3it/s 9.7s
                   all        993       6936      0.766      0.653      0.739      0.538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30      2.87G      1.028      1.032      1.179         18        640: 100% ━━━━━━━━━━━━ 249/249 3.6it/s 1:09
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.8it/s 11.4s
                   all        993       6936       0.74       0.68      0.739      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30      2.87G      1.022       1.02      1.172          3        640: 100% ━━━━━━━━━━━━ 249/249 3.8it/s 1:06
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.8it/s 11.4s
                   all        993       6936      0.791       0.64       0.74       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30      2.87G      1.021      1.012      1.173         12        640: 100% ━━━━━━━━━━━━ 249/249 3.8it/s 1:06
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.8it/s 11.4s
                   all        993       6936      0.766      0.662      0.739       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30      2.87G      1.012       1.01      1.166         11        640: 100% ━━━━━━━━━━━━ 249/249 3.8it/s 1:05
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.9it/s 11.1s
                   all        993       6936      0.782      0.649       0.74      0.541

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30      2.87G      1.012     0.9964      1.165         24        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.3it/s 9.8s
                   all        993       6936      0.789      0.648      0.744      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30      2.87G      1.008     0.9893      1.163         24        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.1it/s 10.4s
                   all        993       6936      0.787      0.647      0.742      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30      2.87G      1.008     0.9945      1.162         12        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.9it/s 10.9s
                   all        993       6936      0.773      0.658      0.742      0.541

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30      2.87G     0.9941     0.9754      1.152          4        640: 100% ━━━━━━━━━━━━ 249/249 3.8it/s 1:06
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.9it/s 11.2s
                   all        993       6936      0.781      0.653      0.743      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30      2.87G      1.004     0.9801      1.161         10        640: 100% ━━━━━━━━━━━━ 249/249 3.8it/s 1:05
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.8it/s 11.5s
                   all        993       6936      0.797      0.641      0.741      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30      2.87G      1.006     0.9795      1.159         11        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.0it/s 10.7s
                   all        993       6936      0.804      0.637      0.742      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30      2.87G     0.9946     0.9606       1.15         31        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.3it/s 9.6s
                   all        993       6936      0.784      0.653      0.741      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30      2.87G      0.994     0.9678       1.15         11        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:07
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.9it/s 11.2s
                   all        993       6936      0.819      0.626      0.742      0.541

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30      2.87G     0.9967     0.9618      1.154         10        640: 100% ━━━━━━━━━━━━ 249/249 3.8it/s 1:06
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.8it/s 11.3s
                   all        993       6936      0.812      0.635       0.74      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30      2.87G     0.9927     0.9661      1.153          8        640: 100% ━━━━━━━━━━━━ 249/249 3.8it/s 1:06
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.9it/s 11.1s
                   all        993       6936       0.79       0.65      0.743      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30      2.87G          1     0.9703      1.156         16        640: 100% ━━━━━━━━━━━━ 249/249 3.7it/s 1:08
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.5s
                   all        993       6936      0.761      0.664      0.741      0.542
EarlyStopping: Training stopped early as no improvement observed in last 10 epochs. Best results observed at epoch 14, best model saved as best.pt.
To update EarlyStopping(patience=10) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

24 epochs completed in 0.524 hours.
Optimizer stripped from /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/treinamento/weights/last.pt, 6.2MB
Optimizer stripped from /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/treinamento/weights/best.pt, 6.2MB

Validating /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/treinamento/weights/best.pt...
Ultralytics 8.4.150 🚀 Python-3.13.15 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,007,988 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 2.1it/s 15.0s
                   all        993       6936      0.786      0.648      0.743      0.544
                   bed        137        210      0.893      0.562      0.717      0.509
                  sofa        367        524      0.844      0.855      0.891      0.719
                 chair        525       2595      0.811      0.481      0.671      0.416
                 table        610       1053      0.828      0.644      0.763      0.555
                  lamp        286        480      0.796      0.609      0.689      0.462
                    tv         85         91      0.811      0.681      0.769      0.612
                laptop         24         30      0.712        0.4      0.494      0.333
              wardrobe         81         95      0.752        0.6      0.728      0.572
                window        146        325       0.72      0.828      0.876      0.658
                  door        182        212      0.632      0.486       0.59      0.428
          potted plant        316        823      0.813       0.74      0.821      0.523
           photo frame        212        498      0.816      0.888      0.912      0.745
Speed: 0.2ms preprocess, 5.9ms inference, 0.0ms loss, 2.6ms postprocess per image
Results saved to /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/treinamento
Novo candidato preservado: /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/best.pt

## 6. Comparar com o antigo na mesma validação

O `best.pt` é escolhido pelo critério padrão do Ultralytics na validação mista;
não é necessariamente a época de maior precisão dos alertas. A comparação
abaixo verifica se ele atende ao objetivo do projeto. Não aumente a confiança
com base no TEST para fazer a precisão parecer maior.

In [8]:
candidato = YOLO(str(PASTA_RESULTADOS / "best.pt"))
metricas_candidato = {**avaliar_detector_val(candidato, "candidato_home_val"),
                      **avaliar_alertas(candidato, REGISTROS_HOME_VAL, NOMES)}
(PASTA_RESULTADOS / "metricas_candidato_val.json").write_text(json.dumps(metricas_candidato, indent=2, ensure_ascii=False), encoding="utf-8")
chaves = ["precision_detector", "recall_detector", "map50", "map50_95",
          "precision_alertas", "recall_alertas", "f1_alertas", "fn", "fp", "alta_sem_alerta"]
comparacao = pd.DataFrame([
    {"metrica": k, "antigo": metricas_antigo[k], "candidato": metricas_candidato[k],
     "diferenca": None if metricas_antigo[k] is None or metricas_candidato[k] is None else metricas_candidato[k] - metricas_antigo[k]}
    for k in chaves
])
display(comparacao)
comparacao.to_csv(PASTA_RESULTADOS / "comparacao_validacao.csv", index=False, encoding="utf-8-sig")
pa, pn = metricas_antigo["precision_alertas"], metricas_candidato["precision_alertas"]
ra, rn = metricas_antigo["recall_alertas"], metricas_candidato["recall_alertas"]
promissor = all(v is not None for v in [pa, pn, ra, rn]) and pn > pa and rn >= ra and metricas_candidato["alta_sem_alerta"] <= metricas_antigo["alta_sem_alerta"]
triagem = {"promissor_na_validacao": bool(promissor),
           "criterio": "Precisão dos alertas maior, Recall não menor e omissões de alta prioridade não maiores, em Home VAL.",
           "observacao": "Triagem exploratória; não é teste de significância nem validação de risco real. Histórico do baseline pode incluir parte do Home VAL atual.",
           "proximo_passo": "Comparar antigo e candidato no 05d local, com TEST e parâmetros preservados; não substituir o baseline automaticamente."}
(PASTA_RESULTADOS / "triagem_validacao.json").write_text(json.dumps(triagem, ensure_ascii=False, indent=2), encoding="utf-8")
print(json.dumps(triagem, ensure_ascii=False, indent=2))
print("Resultados:", PASTA_RESULTADOS)


# Registra o desempenho do candidato no mesmo conjunto que selecionou a época.
metricas_candidato_misto = avaliar_detector_val(candidato, "candidato_misto_val", YAML_MISTO)
(PASTA_RESULTADOS / "metricas_candidato_misto_val.json").write_text(
    json.dumps(metricas_candidato_misto, ensure_ascii=False, indent=2), encoding="utf-8")

# Comparação adicional com o ajuste anterior (0.0003), sem usar seu best.pt
# para inicializar o treinamento e sem misturar suas métricas com o TEST.
arquivo_controle = PASTA_ANTERIOR / "comparacao_validacao.csv"
if arquivo_controle.is_file():
    primeira = pd.read_csv(arquivo_controle)
    if primeira["metrica"].duplicated().any():
        raise RuntimeError("Relatório anterior tem métricas duplicadas.")
    referencia = primeira.set_index("metrica")
    linhas = []
    for k in chaves:
        if k not in referencia.index:
            raise RuntimeError(f"Métrica ausente no relatório anterior: {k}")
        antes = float(referencia.loc[k, "candidato"])
        agora = metricas_candidato[k]
        linhas.append({"metrica": k, "antigo_nesta_execucao": metricas_antigo[k],
                       "primeiro_ajuste_lr_0003": antes,
                       "novo_ajuste_lr_00003": agora,
                       "diferenca_entre_ajustes": None if agora is None else agora - antes})
    evolucao = pd.DataFrame(linhas)
    evolucao.to_csv(PASTA_RESULTADOS / "comparacao_tres_modelos_validacao.csv",
                   index=False, encoding="utf-8-sig")
    display(evolucao)
else:
    print("Relatório anterior não localizado; a comparação principal com o antigo foi salva normalmente.")

Ultralytics 8.4.150 🚀 Python-3.13.15 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,007,988 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2322.6±816.2 MB/s, size: 163.5 KB)
val: Scanning /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train... 456 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 456/456 2.0Kit/s 0.2s
val: New cache created: /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 2.8it/s 10.4s
                   all        456       3682      0.865       0.73      0.837      0.637
                   bed         29         29      0.916      0.759       0.83      0.708
                  sofa        294        420      0.898      0.912      0.945      0.766
                 chair        200        428      0.903      0.738      0.884      0.673
                 table        331        513      0.922      0.807      0.911      0.715
                  lamp        216        370      0.843      0.659      0.765      0.524
                    tv         63         67       0.91      0.746      0.896       0.71
                laptop         17         23       0.77      0.478      0.613      0.435
              wardrobe         80         94      0.837      0.606      0.755      0.588
                window        144        323      0.778      0.814      0.889      0.668
                  door         74         94      0.787      0.649      0.784       0.57
          potted plant        316        823        0.9      0.708      0.845      0.538
           photo frame        212        498      0.918      0.882       0.93      0.756
Speed: 2.1ms preprocess, 4.3ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/candidato_home_val
Validação dos alertas: 100/456
Validação dos alertas: 200/456
Validação dos alertas: 300/456
Validação dos alertas: 400/456

              metrica      antigo   candidato  diferenca
0  precision_detector    0.882927    0.865007  -0.017920
1     recall_detector    0.765052    0.729839  -0.035213
2               map50    0.859207    0.837320  -0.021888
3            map50_95    0.664002    0.637415  -0.026588
4   precision_alertas    0.783646    0.771870  -0.011776
5      recall_alertas    0.899023    0.879479  -0.019544
6          f1_alertas    0.837379    0.822168  -0.015211
7                  fn  155.000000  185.000000  30.000000
8                  fp  381.000000  399.000000  18.000000
9     alta_sem_alerta   24.000000   25.000000   1.000000

{
  "promissor_na_validacao": false,
  "criterio": "Precisão dos alertas maior, Recall não menor e omissões de alta prioridade não maiores, em Home VAL.",
  "observacao": "Triagem exploratória; não é teste de significância nem validação de risco real. Histórico do baseline pode incluir parte do Home VAL atual.",
  "proximo_passo": "Comparar antigo e candidato no 05d local, com TEST e parâmetros preservados; não substituir o baseline automaticamente."
}
Resultados: /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209
Ultralytics 8.4.150 🚀 Python-3.13.15 torch-2.11.0+cu130 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,007,988 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3590.1±1152.6 MB/s, size: 170.1 KB)
val: Scanning /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train... 993 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 993/993 2.0Kit/s 0.5s
val: New cache created: /content/tcc_sunrgbd/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/homeobjects_yolo/labels/val/raw_train.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 63/63 4.2it/s 14.9s
                   all        993       6936      0.788      0.649      0.745      0.545
                   bed        137        210      0.888      0.562      0.718      0.509
                  sofa        367        524      0.844      0.857      0.892      0.719
                 chair        525       2595      0.811      0.483      0.672      0.416
                 table        610       1053      0.829      0.644      0.762      0.555
                  lamp        286        480      0.796      0.611      0.691      0.463
                    tv         85         91      0.806      0.681       0.77      0.613
                laptop         24         30      0.753        0.4      0.498      0.339
              wardrobe         81         95       0.75        0.6      0.727      0.567
                window        146        325      0.716      0.828      0.877      0.658
                  door        182        212      0.635      0.491      0.593       0.43
          potted plant        316        823      0.814      0.742      0.822      0.525
           photo frame        212        498      0.814      0.888      0.912      0.743
Speed: 1.3ms preprocess, 3.5ms inference, 0.0ms loss, 2.2ms postprocess per image
Results saved to /content/drive/MyDrive/TCC_Visao_Computacional/resultados/yolov8n_baseline_sunrgbd_lr_menor_20261013_135714_168209/candidato_misto_val

,metrica,antigo_nesta_execucao,primeiro_ajuste_lr_0003,novo_ajuste_lr_00003,diferenca_entre_ajustes
0,precision_detector,0.882927,0.800123,0.865007,0.064884
1,recall_detector,0.765052,0.735975,0.729839,-0.006136
2,map50,0.859207,0.819436,0.837320,0.017884
3,map50_95,0.664002,0.616436,0.637415,0.020978
4,precision_alertas,0.783646,0.746674,0.771870,0.025196
5,recall_alertas,0.899023,0.877524,0.879479,0.001954
6,f1_alertas,0.837379,0.806828,0.822168,0.015340
7,fn,155.000000,188.000000,185.000000,-3.000000
8,fp,381.000000,457.000000,399.000000,-58.000000
9,alta_sem_alerta,24.000000,28.000000,25.000000,-3.000000

## 7. Enviar resultados e escolher o próximo passo

Arquivos para documentar o experimento 07b, na pasta de resultados do Drive:

- `configuracao_experimento.json`;
- `comparacao_validacao.csv`;
- `triagem_validacao.json`;
- `treinamento/results.csv` (a curva completa de épocas);
- `comparacao_tres_modelos_validacao.csv`, quando produzido;
- `metricas_baseline_misto_val.json` e `metricas_candidato_misto_val.json`.

Se houver ganho na validação, avaliamos o candidato no 05d local. Para esse
passo futuro, o caminho separado será `models/yolov8n_baseline_sunrgbd_lr_menor_01/best.pt`.
O antigo permanece como referência atual. Uma melhora apenas em relação
ao primeiro ajuste ainda não demonstra que o candidato superou o antigo.

O TEST já foi usado em comparações anteriores. Ele segue como benchmark fixo;
a escolha de taxa, classes e dados usa apenas desenvolvimento e validação.
A comparação Home VAL é exploratória, pois o baseline pode ter visto parte
desse conjunto no seu treinamento original. Não é validação independente
de risco físico. A política V2 produz os mesmos tipos de mensagens em texto.